# FlagGame Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/FlagGame

#==================#
#   Basic Config   #
#==================#
# ItemID, used to create/remove Flag blocks
ToolID: 269
# FlagGame World
WorldName: flag
# If it true, Gameworld will be protected by player
WorldProtect: false
# Use debug mode
Debug: false
# Use dynmap layer for show stage information?
UseDynmap: false

#==================#
#   Games Config   #
#==================#
# Countdown time(sec) when starting the game
StartCountdownInSec: 10
# If it true, Play effects when place/break flag
UseFlagEffects: true
# If it true, Kills player when logout during the game
DeathWhenLogout: true
# If it true, Same teams damage will be disabled
DisableTeamPVP: true
# If it true, Prevent regain health on game world
DisableRegainHealth: true
# Prevents respawn kill, god-mode time in ticks
RespawnGodModeTime: 80
# Lists of disabled commands during the game
DisableCommands:
- /spawn
- /home
- /sethome
- /warp
- /tp
- /pot
- /flymode
- /fm

#==================#
#  MongoDB Config  #
#==================#
Database:
  Address: localhost
  Port: 27017
  Name: flaggame
  User_Name: null
  User_Password: null

#====================#
#   Logging Config   #
#====================#
# DetailLogDirectory
DetailDirectory: plugins/FlagGame/detail/

#========================#
#   Permissions Config   #
#========================#
# Use Permissions List
Permissions:
- vault
- superperms
- ops

#========================#
#   Score weight Config   #
#========================#
score:
  game:
    join: 10.0
    exit: -10.0
  combat:
    kill: 0.5
    death: 0.0
  flag:
    place: 1.0
    last_place: 5.0
    break: 1.0
  banner:
    deploy: 3.0
    get: 0.1
    keep: 3.0
    steal: 0.25
  nexus:
    break: 1.0
  rate: 5.0

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.5